#!/bin/bash
# 2018-01-13
# Feeder to the slo queue (Lots of files Opener)
# Use as: lo <part of filename(s)>
# Adds to the beginning of the queue.

if ! pgrep -x "slo" > /dev/null
then
 echo "I need the slo server running but it's apparently not."
fi

if [[ "$1" == "http://"* ]] || [[ "$1" == "https://"* ]]
then
 if [ -s $HOME/.slo/2p.txt ]
 then
  echo "$1
$(cat $HOME/.slo/2p.txt)" > $HOME/.slo/2p.txt
 else
  echo "$1" > $HOME/.slo/2p.txt
 fi
 sleep 0.3 #Don't interfere with slo processing a new list
else
 for j in "$@"
 do
  for i in *$j*
  do
   k=`date +%N`
   # Alpine is crazy
   clfn=${i//\*/}
   veg=${clfn##*.}
   elej=${clfn%.*}
   #gnome-terminal -e "bash -c 'echo "$clfn"; exec bash'"

   clfnr="${elej}_${k}.${veg}"

   pfn=${clfnr##*/}
   cp "$clfn" $HOME/.slo/2p/"$pfn"
   if [ -s $HOME/.slo/2p.txt ]
   then
    echo "$pfn
$(cat $HOME/.slo/2p.txt)" > $HOME/.slo/2p.txt
   else
    echo "$pfn" > $HOME/.slo/2p.txt
   fi
   sleep 0.3 #Don't interfere with slo processing a new list
  done
 done
fi
