#!/bin/bash
# 2018-01-13
# Feeder to the slo queue (Lots of files Opener)
# Use as: lo2e <part of filename(s)>

if ! pgrep -x "slo" > /dev/null
then
 echo "I need the slo server running but it's apparently not."
fi

if [[ "$1" == "http://"* ]] || [[ "$1" == "https://"* ]]
then
 echo "$1" >> $HOME/.slo/2p.txt
 #silent_cpucsekk #No need to wait if writing at end of file
else
 for j in "$@"
 do
  for i in *$j*
  do
   #k=`date +%N`
   k=`date +%y%m%d_%H%M%S`_`strings /dev/urandom | tr -dc a-z-0-9 | tr -d - | head -c5`
   # Alpine is crazy
   clfn=${i//\*/}
   veg=${clfn##*.}
   elej=${clfn%.*}
   #gnome-terminal -e "bash -c 'echo "$clfn"; exec bash'"

   clfnr="${elej}_${k}.${veg}"

   pfn=${clfnr##*/}
   cp "$clfn" $HOME/.slo/2p/"$pfn"
   echo "$pfn" >> $HOME/.slo/2p.txt
   #silent_cpucsekk #No need to wait if writing at end of file
  done
 done
fi
