#!/bin/bash
# Printer can be specified in file ~/.prevlpr_printer.txt
# converts things to ps, shows them, prints them.
# Obviously, if you prefer psbinding a print then you need psbind in the path. http://freecode.com/projects/psbind

function exitcl {
 cd -

 l=1
 while [ -n "$l" ]; do
  sleep 1
  l=`lsof 2>/dev/null +d /tmp/$k`
 done

 rm -f -R /tmp/$k
 exit
}

if [ -f ~/.prevlpr_printer.txt ]; then
 printer=`cat ~/.prevlpr_printer.txt`
else
 printer=""
fi

for j in "$@"
do
 for i in *$j*
 do
 
# Bash parameter expansion
  veg=${i##*.}
  elej=${i%.*}

  if [[ "$veg" == "pdf" ]] || [[ "$veg" == "PDF" ]] || [[ "$veg" == "ps" ]] || [[ "$veg" == "PS" ]] || [[ "$veg" == "doc" ]] || [[ "$veg" == "docx" ]] || [[ "$veg" == "rtf" ]] || [[ "$veg" == "ods" ]] || [[ "$veg" == "odt" ]] || [[ "$veg" == "xls" ]] || [[ "$veg" == "xlsx" ]] || [[ "$veg" == "xlsm" ]] || [[ "$veg" == "ppt" ]] || [[ "$veg" == "pptx" ]] || [[ "$veg" == "pps" ]] || [[ "$veg" == "csv" ]] || [[ "$veg" == "txt" ]] || [[ "$veg" == "tex" ]] || [[ "$veg" == "ltx" ]] || [[ "$veg" == "html" ]] || [[ "$veg" == "htm" ]]; then
   #k=v3$elej`date +%N`
   k=v3$elej`date +%y%m%d_%H%M%S`_`strings /dev/urandom | tr -dc a-z-0-9 | tr -d - | head -c5`
   mkdir /tmp/$k
   chmod 700 /tmp/$k/
 
   cp "$i" /tmp/$k
   catthatfile "/tmp/$k" "$i" &
   cd /tmp/$k

# Convert to ps
   if [[ "$veg" == "pdf" ]] || [[ "$veg" == "PDF" ]]; then
    command -v pdftops > /dev/null 2>&1
    if [ "$?" -ne "0" ]; then
     echo "I need pdftops but I can't find it."
     exitcl
    fi
    pdftops "$i"
   fi
   if [[ "$veg" == "doc" ]] || [[ "$veg" == "docx" ]] || [[ "$veg" == "rtf" ]] || [[ "$veg" == "ods" ]] || [[ "$veg" == "odt" ]] || [[ "$veg" == "xls" ]] || [[ "$veg" == "xlsx" ]] || [[ "$veg" == "xlsm" ]] || [[ "$veg" == "ppt" ]] || [[ "$veg" == "pptx" ]] || [[ "$veg" == "pps" ]] || [[ "$veg" == "csv" ]]; then
    command -v libreoffice > /dev/null 2>&1
    if [ "$?" -ne "0" ]; then
     echo "I need libreoffice but I can't find it."
     exitcl
    fi
    command -v pdftops > /dev/null 2>&1
    if [ "$?" -ne "0" ]; then
     echo "I need pdftops but I can't find it."
     exitcl
    fi
    libreoffice --headless --convert-to pdf "$i"
    pdftops "$elej.pdf"
   fi
   if [[ "$veg" == "txt" ]]; then
    command -v a2ps > /dev/null 2>&1
    if [ "$?" -ne "0" ]; then
     echo "I need a2ps but I can't find it."
     exitcl
    fi
    a2ps -o "$elej.ps" "$i" 
   fi
   if [[ "$veg" == "PS" ]]; then
    cp "$i" "$elej.ps"
   fi
   if [[ "$veg" == "tex" ]] || [[ "$veg" == "ltx" ]]; then
    command -v latex > /dev/null 2>&1
    if [ "$?" -ne "0" ]; then
     echo "I need LaTeX but I can't find it."
     exitcl
    fi
    cd -
    cp *.bib /tmp/$k
    cp *.png /tmp/$k
    cp *.pdf /tmp/$k
    cp *.eps /tmp/$k
    cp *.epsi /tmp/$k
    cp *.ps /tmp/$k
    cp *.clo /tmp/$k
    cp *.cls /tmp/$k
    cp *.bst /tmp/$k
    cp *.sty /tmp/$k
    cd /tmp/$k

# Do we have solutions?
    solutions=0
    if grep -q "setbool{solu}{true}" "$i"
    then
     solutions=1
    fi
 
    if grep -q "setbool{solu}{false}" "$i"
    then
     solutions=1
    fi
 
    if grep -q "setbool{fullsolu}{true}" "$i"
    then
     solutions=2
    fi
 
    if grep -q "setbool{fullsolu}{false}" "$i"
    then
     solutions=2
    fi
 
    if [ "$solutions" -eq "1" ]
    then
     read -p "This file has solutions [s] or no solutions [n] versions. Hit s or n, or else keep the original.
     " solnosol

     if [ "$solnosol" == "s" ]
     then
      cat $i |
      awk ' BEGIN{ 
       soldone=0
      }
      {
       if ($0=="\%\\setbool{solu}{true}" || $0=="\\setbool{solu}{true}" || $0=="\%\\setbool{solu}{false}" || $0=="\\setbool{solu}{false}") {
        if (soldone==0) {
         print("\\setbool{solu}{true}");
         soldone=1
        };
       }
       else {
        print($0)
       };
      }' > sol_"$i"

      mv sol_"$i" "$i"
     fi

     if [ "$solnosol" == "n" ]
     then
      cat $i |
      awk ' BEGIN{ 
       soldone=0
      }
      {
       if ($0=="\%\\setbool{solu}{true}" || $0=="\\setbool{solu}{true}" || $0=="\%\\setbool{solu}{false}" || $0=="\\setbool{solu}{false}") {
        if (soldone==0) {
         print("\\setbool{solu}{false}");
         soldone=1
        };
       }
       else {
        print($0)
       };
      }' > nosol_"$i"

      mv nosol_"$i" "$i"
     fi

    fi

    if [ "$solutions" -eq "2" ]
    then
     read -p "This file has full solutions [f] or solutions [s] or no solutions [n] versions. Hit f s or n, or else keep the original.
     " solnosol

     if [ "$solnosol" == "s" ]
     then
      cat $i |
      awk ' BEGIN{ 
       soldone=0
       fullsoldone=0
      }
      {
       if ($0=="\%\\setbool{solu}{true}" || $0=="\\setbool{solu}{true}" || $0=="\%\\setbool{solu}{false}" || $0=="\\setbool{solu}{false}") {
        if (soldone==0) {
         print("\\setbool{solu}{true}");
         soldone=1
        };
       }
       else if ($0=="\%\\setbool{fullsolu}{true}" || $0=="\\setbool{fullsolu}{true}" || $0=="\%\\setbool{fullsolu}{false}" || $0=="\\setbool{fullsolu}{false}") {
        if (fullsoldone==0) {
         print("\\setbool{fullsolu}{false}");
         fullsoldone=1
        };
       }
       else {
        print($0)
       };
      }' > sol_"$i"

      mv sol_"$i" "$i"
     fi

     if [ "$solnosol" == "n" ]
     then
      cat $i |
      awk ' BEGIN{ 
       soldone=0
       fullsoldone=0
      }
      {
       if ($0=="\%\\setbool{solu}{true}" || $0=="\\setbool{solu}{true}" || $0=="\%\\setbool{solu}{false}" || $0=="\\setbool{solu}{false}") {
        if (soldone==0) {
         print("\\setbool{solu}{false}");
         soldone=1
        };
       }
       else if ($0=="\%\\setbool{fullsolu}{true}" || $0=="\\setbool{fullsolu}{true}" || $0=="\%\\setbool{fullsolu}{false}" || $0=="\\setbool{fullsolu}{false}") {
        if (fullsoldone==0) {
         print("\\setbool{fullsolu}{false}");
         fullsoldone=1
        };
       }
       else {
        print($0)
       };
      }' > nosol_"$i"

      mv nosol_"$i" "$i"
     fi

     if [ "$solnosol" == "f" ]
     then
      cat $i |
      awk ' BEGIN{ 
       soldone=0
       fullsoldone=0
      }
      {
       if ($0=="\%\\setbool{solu}{true}" || $0=="\\setbool{solu}{true}" || $0=="\%\\setbool{solu}{false}" || $0=="\\setbool{solu}{false}") {
        if (soldone==0) {
         print("\\setbool{solu}{true}");
         soldone=1
        };
       }
       else if ($0=="\%\\setbool{fullsolu}{true}" || $0=="\\setbool{fullsolu}{true}" || $0=="\%\\setbool{fullsolu}{false}" || $0=="\\setbool{fullsolu}{false}") {
        if (fullsoldone==0) {
         print("\\setbool{fullsolu}{true}");
         fullsoldone=1
        };
       }
       else {
        print($0)
       };
      }' > fullsol_"$i"

      mv fullsol_"$i" "$i"
     fi

    fi

    latex -interaction=nonstopmode "$i"
    
    cd -
    if [[ -f "$elej".bbl ]]
    then
     cp "$elej".bbl /tmp/$k
     cd /tmp/$k
    else
     cd /tmp/$k
     bibtex "$elej".aux
    fi
    makeindex "$elej"
    latex -interaction=nonstopmode "$i"
    latex -interaction=nonstopmode "$i"
    latex -interaction=nonstopmode "$i"
    dvips "$elej".dvi
   fi
   if [[ "$veg" == "html" ]] || [[ "$veg" == "html" ]]; then
    command -v html2ps > /dev/null 2>&1
    if [ "$?" -ne "0" ]; then
     echo "I need html2ps but I can't find it."
     exitcl
    fi
    html2ps "$i" > "$elej.ps"
   fi

# Show result
   gv "$elej.ps" &
   read -p "How do you like the ps? o: ok, print it (duplex printer); s: short edge print it (duplex printer); t: two sided print on simple printer; p: psbind it; e: prepare pdf for email printing; f: same w/ even pages upside-down; n: no options to lpr; anything else to forget it.
   " tetszik

# If ok:
   if [ "$tetszik" == "o" ]; then
    if [ "$printer" == "" ]; then
     lpr -o sides=two-sided-long-edge "$elej.ps"
     echo "Sent $elej.ps to printer."
    else
     lpr -o sides=two-sided-long-edge -P"$printer" "$elej.ps"
     echo "Sent $elej.ps to $printer."
    fi

   elif [ "$tetszik" == "n" ]; then
    if [ "$printer" == "" ]; then
     lpr "$elej.ps"
     echo "Sent $elej.ps to printer."
    else
     lpr -P"$printer" "$elej.ps"
     echo "Sent $elej.ps to $printer."
    fi

   elif [ "$tetszik" == "s" ]; then
    if [ "$printer" == "" ]; then
     lpr -o sides=two-sided-short-edge "$elej.ps"
#https://dvinfo.ifh.de/Printing_with_Cups#I.27m_using_psutils_.28pstops.2Cpsnup.2Cpsbook.29._Even_though_I.27m_using_the_option_.27.27sides.3Dtwo-sided-short-edge.27.27_the_output_was_not_arranged_in_the_correct_order._What_can_I_do.3F
     #lp -o document-format=application/bindshort "$elej.ps"
     echo "Sent $elej.ps to printer (short edge)."
    else
     lpr -o sides=two-sided-short-edge -P"$printer" "$elej.ps"
     #lp -o document-format=application/bindshort -d"$printer" "$elej.ps"
     echo "Sent $elej.ps to $printer (short edge)."
    fi

   elif [ "$tetszik" == "t" ]; then
    if [ "$printer" == "" ]; then
     psselect -e -r "$elej.ps" | lpr
     echo "Sent the even pages of $elej.ps to printer."
     echo "Turn sheets in their plane and refeed, press [enter] when ready."
     read
     psselect -o "$elej.ps" | lpr
     echo "Sent the odd pages of $elej"_"$k.ps to printer."
    else
     psselect -e -r "$elej.ps" | lpr -P"$printer"
     echo "Sent the even pages of $elej.ps to $printer."
     echo "Turn sheets in their plane and refeed, press [enter] when ready."
     read
     psselect -o "$elej.ps" | lpr -P"$printer"
     echo "Sent the odd pages of $elej"_"$k.ps to $printer."
    fi

   elif [ "$tetszik" == "e" ]; then
    ps2pdf "$elej.ps" "$elej"_email.pdf
    cpcl "$elej"_email.pdf
    zathura "$elej"_email.pdf
    #evince "$elej"_email.pdf
    #xpdf "$elej"_email.pdf

   elif [ "$tetszik" == "f" ]; then
    ps2pdf "$elej.ps" "$elej"_torot.pdf
    pdftk A="$elej"_torot.pdf shuffle Aodd Aevensouth output "$elej"_email.pdf
    cpcl "$elej"_email.pdf
    zathura "$elej"_email.pdf
    #evince "$elej"_email.pdf
    #xpdf "$elej"_email.pdf


# If psbind:
   elif [ "$tetszik" == "p" ]; then
    psbind "$elej.ps" > "$elej"_"$k.ps"
    gv "$elej"_"$k.ps" &
    read -p "How do you like the psbinded ps? o: ok, print it; s: long edge print it; t: two sided print on simple printer, e: prepare pdf for email printing; f: same w/ even pages upside-down; n: no options to lpr; anything else to forget it.
    " tetszikp

    if [ "$tetszikp" == "o" ]; then
     if [ "$printer" == "" ]; then
      lpr -o sides=two-sided-short-edge "$elej"_"$k.ps"
      #lp -o document-format=application/bindshort "$elej"_"$k.ps"
      echo "Sent $elej"_"$k.ps to printer."
     else
      lpr -o sides=two-sided-short-edge -P"$printer" "$elej"_"$k.ps"
      #lp -o document-format=application/bindshort -d"$printer" "$elej"_"$k.ps"
      echo "Sent $elej"_"$k.ps to $printer."
     fi

    elif [ "$tetszikp" == "n" ]; then
     if [ "$printer" == "" ]; then
      lpr "$elej"_"$k.ps"
      echo "Sent $elej"_"$k.ps to printer."
     else
      lpr -P"$printer" "$elej"_"$k.ps"
      echo "Sent $elej"_"$k.ps to $printer."
     fi

    elif [ "$tetszikp" == "s" ]; then
     if [ "$printer" == "" ]; then
      lpr -o sides=two-sided-long-edge "$elej"_"$k.ps"
      echo "Sent $elej"_"$k.ps to printer (long edge)."
     else
      lpr -o sides=two-sided-long-edge -P"$printer" "$elej"_"$k.ps"
      echo "Sent $elej"_"$k.ps to $printer (long edge)."
     fi

    elif [ "$tetszikp" == "t" ]; then
     if [ "$printer" == "" ]; then
      psselect -e -r "$elej"_"$k.ps" | lpr
      echo "Sent the even pages of $elej"_"$k.ps to printer."
      echo "Refeed sheets without turning, press [enter] when ready."
      read
      psselect -o "$elej"_"$k.ps" | lpr
      echo "Sent the odd pages of $elej"_"$k.ps to printer."
     else
      psselect -e -r "$elej"_"$k.ps" | lpr -P"$printer"
      echo "Sent the even pages of $elej"_"$k.ps to $printer."
      echo "Refeed sheets without turning, press [enter] when ready."
      read
      psselect -o "$elej"_"$k.ps" | lpr -P"$printer"
      echo "Sent the odd pages of $elej"_"$k.ps to $printer."
     fi

    elif [ "$tetszikp" == "e" ]; then
     ps2pdf "$elej"_"$k.ps" "$elej"_email.pdf
     cpcl "$elej"_email.pdf
     zathura "$elej"_email.pdf
     #evince "$elej"_email.pdf
     #xpdf "$elej"_email.pdf

    elif [ "$tetszikp" == "f" ]; then
     ps2pdf "$elej"_"$k.ps" "$elej"_torot.pdf
     pdftk A="$elej"_torot.pdf shuffle Aodd Aevensouth output "$elej"_email.pdf
     cpcl "$elej"_email.pdf
     zathura "$elej"_email.pdf
     #evince "$elej"_email.pdf
     #xpdf "$elej"_email.pdf

    else
     echo "Ok, forget it."
    fi

# If not nice:
   else
    echo "Ok, forget it."
   fi

   exitcl
  fi
 done
done
