#!/bin/bash
# Usage: szerk [any number of strings]
# opens and edits all files (of types below) that have any of the strings in their names, then copies them back to their original locations.
# notice: mybr is a script in your path for launching your favourite browser. Could as well replace by e.g. "firefox" or "chromium-browser".

# Work directory (for example, $HOME/tmp or /tmp):
wkdir="$HOME/a"

for j in "$@"
do
 for i in *$j*
 do
  firstfile=i
  break
 done
 break
done
legelej=${i%.*}
#k=s3$legelej`date +%N`
k=s3$legelej`date +%y%m%d_%H%M%S`_`strings /dev/urandom | tr -dc a-z-0-9 | tr -d - | head -c5`
mkdir $wkdir/$k
chmod 700 $wkdir/$k/

viml=""
ffl=""
ool=""
files=""

for j in "$@"
do

 for i in *$j*
 do
 
  if [ ! -f "$i" ]
  then
   continue
  fi

  if [ ! -w "$i" ]
  then
   read -p "$i non-writable, [Enter]"
   continue
  fi

  if [ -f ".szerklock_$i" ]
  then
   echo Found ".szerklock_$i, skipping $i"
   continue
  else
   touch ".szerklock_$i"
  fi

 # Bash parameter expansion
   veg=${i##*.}
   elej=${i%.*}
  
 #echo "$veg"
 #echo "$elej"
  
 #### doc, docx, rtf, ods, odt, xls, xlsx, xlsm, ppt, pptx, pps
  
  if [[ "$veg" == "doc" ]] || [[ "$veg" == "docx" ]] || [[ "$veg" == "rtf" ]] || [[ "$veg" == "ods" ]] || [[ "$veg" == "odt" ]] || [[ "$veg" == "xls" ]] || [[ "$veg" == "xlsx" ]] || [[ "$veg" == "xlsm" ]] || [[ "$veg" == "ppt" ]] || [[ "$veg" == "pptx" ]] || [[ "$veg" == "pps" ]]
  then
   cp "$i" $wkdir/$k
   catthatfile "$wkdir/$k" "$i" &
   cd $wkdir/$k
 
   ool="$i $ool"
   files="$i $files"
 
   cd -
  fi 
  
 #### htm, html, wml
  
  if [[ "$veg" == "htm" ]] || [[ "$veg" == "html" ]] || [[ "$veg" == "wml" ]]
  then
   cp "$i" $wkdir/$k
   catthatfile "$wkdir/$k" "$i" &
   cd $wkdir/$k
 
   viml="$i $viml"
   ffl="$i $ffl"
   files="$i $files"
 
   cd -
  fi
  
 #### lev, txt, org, php, sql, csv, css, sty
  
  if [[ "$veg" == "rnd" ]] || [[ "$veg" == "lev" ]] || [[ "$veg" == "m" ]] || [[ "$veg" == "txt" ]] || [[ "$veg" == "org" ]] || [[ "$veg" == "php" ]] || [[ "$veg" == "sql" ]] || [[ "$i" != *.* ]] || [[ "$veg" == "csv" ]] || [[ "$veg" == "css" ]] || [[ "$veg" == "sty" ]]
  then
   cp "$i" $wkdir/$k
   catthatfile "$wkdir/$k" "$i" &
   cd $wkdir/$k
 
   viml="$i $viml"
   files="$i $files"
 
   cd -
  fi
  
 #### tex, ltx
  
  if [[ "$veg" == "tex" ]] || [[ "$veg" == "ltx" ]]
  then
   cp "$i" $wkdir/$k
   catthatfile "$wkdir/$k" "$i" &
   cp *.bib $wkdir/$k
   if [ "$?" == 0 ]
   then
    files="*.bib $files"
   fi
   cp *.png $wkdir/$k
   if [ "$?" == 0 ]
   then
    files="*.png $files"
   fi
   cp *.pdf $wkdir/$k
   if [ "$?" == 0 ]
   then
    files="*.pdf $files"
   fi
   cp *.eps $wkdir/$k
   if [ "$?" == 0 ]
   then
    files="*.eps $files"
   fi
   cp *.epsi $wkdir/$k
   if [ "$?" == 0 ]
   then
    files="*.epsi $files"
   fi
   cp *.ps $wkdir/$k
   if [ "$?" == 0 ]
   then
    files="*.ps $files"
   fi
   cp *.clo $wkdir/$k
   cp *.cls $wkdir/$k
   cp *.bst $wkdir/$k
   cp *.sty $wkdir/$k
   if [ "$?" == 0 ]
   then
    files="*.sty $files"
   fi
   cd $wkdir/$k
   latex "$i"
   files="$i $files"
   
   cd -
   if [[ -f "$elej".bbl ]]
   then
    cp "$elej".bbl $wkdir/$k
    files="$elej.bbl $files"
    cd $wkdir/$k
   else
    cd $wkdir/$k
    bibtex "$elej".aux
   fi

   makeindex "$elej"
  
   latex "$i"
   latex "$i"
   latex "$i"
   
   #dvipdf "$elej".dvi
   #dvipdfm "$elej".dvi
   dvips "$elej".dvi
   ps2pdf "$elej".ps
  
   cp "$elej".pdf "$elej"_nezd.pdf
  
   zathura >/dev/null 2>&1 "$elej"_nezd.pdf &
   #evince >/dev/null 2>&1 "$elej"_nezd.pdf &
   #xpdf >/dev/null 2>&1 "$elej"_nezd.pdf &
   zathura >/dev/null 2>&1 "$elej".pdf &
   #evince >/dev/null 2>&1 "$elej".pdf &
   #xpdf >/dev/null 2>&1 "$elej".pdf &
 
   viml="$i $viml"
 
   cd -
  fi
  
 #### zhk
  
  if [[ "$veg" == "zhk" ]]
  then
   cp "$elej.zhk" $wkdir/$k
   cp "$elej.kov" $wkdir/$k
   cp "$elej.knv" $wkdir/$k
   catthatfile "$wkdir/$k" "$i" &
   cd $wkdir/$k
 
   zh "$i"
   
   viml="$i $viml"
   ffl="$elej.html $ffl"
   files="$elej.zhk $files"
   files="$elej.kov $files"
   files="$elej.knv $files"
 
   cd -
  fi
 done
done

# open everyone in vim, openoffice and firefox.
cd $wkdir/$k
if [ -n "$ool" ]
then
 libreoffice $ool &
fi
if [ -n "$ffl" ]
then
# notice: mybr is a script in your path for launching your favourite browser. Could as well replace by e.g. "firefox" or "chromium-browser".
 mybr $ffl &
fi
if [ -n "$viml" ]
then
 vim -p $viml
fi

# wait till everything closed
cd -
l=1
while [ -n "$l" ]; do
 sleep 1
 l=`lsof 2>/dev/null +d $wkdir/$k`
#  echo "$wkdir/$k/$elej.$veg nyitva"
done

# Check changes for text edits
for i in $viml
do
 cmp -s $wkdir/$k/$i ./$i
 if [ "$?" -ne "0" ]; then
  vimdiff -R -M ./$i $wkdir/$k/$i
 fi
done

# Copying back
baj=0
for i in $files
do
 cmp -s $wkdir/$k/$i ./$i
 if [ "$?" -ne "0" ]; then
  cp $wkdir/$k/$i .
  if [ "$?" -ne "0" ]
  then
   echo "!!! Problem with $wkdir/$k/$i !!!"
   baj=1
  else
   echo "$wkdir/$k/$i --> $PWD"
  fi
 fi
 while true
 do
  if [ -f ./".szerklock_$i" ]
  then
   echo "Removing .szerklock_$i"
   rm ./".szerklock_$i"
   sleep 1
  else
   break
  fi
 done
done

if [ "$baj" -ne "1" ]
then
 while true
 do
  if [ -d "$wkdir/$k" ]
  then
   echo "Removing $wkdir/$k"
   rm -f -R $wkdir/$k
   sleep 1
  else
   break
  fi
 done
else
 echo "!!! Problem with, $wkdir/$k/ has not been deleted !!!"
fi

