#!/bin/bash
# 2018-01-14
# Usage: szerk [any number of strings]
# opens and edits all files (of types below) that have any of the strings in their names, then copies them back to their original locations.
# notice: mybr is a script in your path for launching your favourite browser. Could as well replace by e.g. "firefox" or "chromium-browser".

for j in "$@"
do
 for i in *$j*
 do
  firstfile=i
  break
 done
 break
done
legelej=${i%.*}
k=s3$legelej`date +%N`
mkdir $HOME/tmp/$k
chmod 700 $HOME/tmp/$k/

viml=""
ffl=""
ool=""
files=""

for j in "$@"
do

 for i in *$j*
 do
 
  if [ ! -f "$i" ]
  then
   continue
  fi

  if [ ! -w "$i" ]
  then
   read -p "$i non-writable, [Enter]"
   continue
  fi

  if [ -f ".szerklock_$i" ]
  then
   echo Found ".szerklock_$i, skipping $i"
   continue
  else
   touch ".szerklock_$i"
  fi

 # Bash parameter expansion
   veg=${i##*.}
   elej=${i%.*}
  
 #echo "$veg"
 #echo "$elej"
  
 #### doc, docx, rtf, ods, odt, xls, xlsx, xlsm, ppt, pptx, pps
  
  if [[ "$veg" == "doc" ]] || [[ "$veg" == "docx" ]] || [[ "$veg" == "rtf" ]] || [[ "$veg" == "ods" ]] || [[ "$veg" == "odt" ]] || [[ "$veg" == "xls" ]] || [[ "$veg" == "xlsx" ]] || [[ "$veg" == "xlsm" ]] || [[ "$veg" == "ppt" ]] || [[ "$veg" == "pptx" ]] || [[ "$veg" == "pps" ]]
  then
   cp "$i" $HOME/tmp/$k
   catthatfile "$HOME/tmp/$k" "$i" &
   cd $HOME/tmp/$k
 
   ool="$i $ool"
   files="$i $files"
 
   cd -
  fi 
  
 #### htm, html, wml
  
  if [[ "$veg" == "htm" ]] || [[ "$veg" == "html" ]] || [[ "$veg" == "wml" ]]
  then
   cp "$i" $HOME/tmp/$k
   catthatfile "$HOME/tmp/$k" "$i" &
   cd $HOME/tmp/$k
 
   viml="$i $viml"
   ffl="$i $ffl"
   files="$i $files"
 
   cd -
  fi
  
 #### lev, txt, org, php, sql, csv, css
  
  if [[ "$veg" == "rnd" ]] || [[ "$veg" == "lev" ]] || [[ "$veg" == "m" ]] || [[ "$veg" == "txt" ]] || [[ "$veg" == "org" ]] || [[ "$veg" == "php" ]] || [[ "$veg" == "sql" ]] || [[ "$i" != *.* ]] || [[ "$veg" == "csv" ]] || [[ "$veg" == "css" ]]
  then
   cp "$i" $HOME/tmp/$k
   catthatfile "$HOME/tmp/$k" "$i" &
   cd $HOME/tmp/$k
 
   viml="$i $viml"
   files="$i $files"
 
   cd -
  fi
  
 #### tex, ltx
  
  if [[ "$veg" == "tex" ]] || [[ "$veg" == "ltx" ]]
  then
   cp "$i" $HOME/tmp/$k
   catthatfile "$HOME/tmp/$k" "$i" &
   cp *.bib $HOME/tmp/$k
   if [ "$?" == 0 ]
   then
    files="*.bib $files"
   fi
   cp *.png $HOME/tmp/$k
   if [ "$?" == 0 ]
   then
    files="*.png $files"
   fi
   cp *.pdf $HOME/tmp/$k
   if [ "$?" == 0 ]
   then
    files="*.pdf $files"
   fi
   cp *.eps $HOME/tmp/$k
   if [ "$?" == 0 ]
   then
    files="*.eps $files"
   fi
   cp *.epsi $HOME/tmp/$k
   if [ "$?" == 0 ]
   then
    files="*.epsi $files"
   fi
   cp *.ps $HOME/tmp/$k
   if [ "$?" == 0 ]
   then
    files="*.ps $files"
   fi
   cp *.clo $HOME/tmp/$k
   cp *.cls $HOME/tmp/$k
   cp *.bst $HOME/tmp/$k
   cp *.sty $HOME/tmp/$k
   if [ "$?" == 0 ]
   then
    files="*.sty $files"
   fi
   cd $HOME/tmp/$k
   latex "$i"
   files="$i $files"
   
   cd -
   if [[ -f "$elej".bbl ]]
   then
    cp "$elej".bbl $HOME/tmp/$k
    files="$elej.bbl $files"
    cd $HOME/tmp/$k
   else
    cd $HOME/tmp/$k
    bibtex "$elej".aux
   fi

   makeindex "$elej"
  
   latex "$i"
   latex "$i"
   latex "$i"
   
   dvipdf "$elej".dvi
  
   cp "$elej".pdf "$elej"_nezd.pdf
  
   zathura >/dev/null 2>&1 "$elej"_nezd.pdf &
   #evince >/dev/null 2>&1 "$elej"_nezd.pdf &
   #xpdf >/dev/null 2>&1 "$elej"_nezd.pdf &
   zathura >/dev/null 2>&1 "$elej".pdf &
   #evince >/dev/null 2>&1 "$elej".pdf &
   #xpdf >/dev/null 2>&1 "$elej".pdf &
 
   viml="$i $viml"
 
   cd -
  fi
  
 #### zhk
  
  if [[ "$veg" == "zhk" ]]
  then
   cp "$elej.zhk" $HOME/tmp/$k
   cp "$elej.kov" $HOME/tmp/$k
   cp "$elej.knv" $HOME/tmp/$k
   catthatfile "$HOME/tmp/$k" "$i" &
   cd $HOME/tmp/$k
 
   zh "$i"
   
   viml="$i $viml"
   ffl="$elej.html $ffl"
   files="$elej.zhk $files"
   files="$elej.kov $files"
   files="$elej.knv $files"
 
   cd -
  fi
 done
done

# open everyone in vim, openoffice and firefox.
cd $HOME/tmp/$k
if [ -n "$ool" ]
then
 libreoffice $ool &
fi
if [ -n "$ffl" ]
then
# notice: mybr is a script in your path for launching your favourite browser. Could as well replace by e.g. "firefox" or "chromium-browser".
 mybr $ffl &
fi
if [ -n "$viml" ]
then
 vim -p $viml
fi

# wait till everything closed
cd -
l=1
while [ -n "$l" ]; do
 sleep 1
 l=`lsof 2>/dev/null +d $HOME/tmp/$k`
#  echo "$HOME/tmp/$k/$elej.$veg nyitva"
done

# Check changes for text edits
for i in $viml
do
 cmp -s $HOME/tmp/$k/$i ./$i
 if [ "$?" -ne "0" ]; then
  vimdiff -R -M ./$i $HOME/tmp/$k/$i
 fi
done

# Copying back
baj=0
for i in $files
do
 cmp -s $HOME/tmp/$k/$i ./$i
 if [ "$?" -ne "0" ]; then
  cp $HOME/tmp/$k/$i .
  if [ "$?" -ne "0" ]
  then
   echo "!!! Problem with $HOME/tmp/$k/$i !!!"
   baj=1
  else
   echo "$HOME/tmp/$k/$i --> $PWD"
  fi
 fi
 if [ -f ./".szerklock_$i" ]
 then
  rm ./".szerklock_$i"
 fi
done

if [ "$baj" -ne "1" ]
then
 rm -f -R $HOME/tmp/$k
else
 echo "!!! Problem with, $HOME/tmp/$k/ has not been deleted !!!"
fi
